# Generated by Django 5.2.6 on 2026-04-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField()),
                ('hero_image', models.URLField()),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('best_time_to_visit', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('travel_start', models.DateField(blank=True, null=True)),
                ('travel_end', models.DateField(blank=True, null=True)),
                ('travel_month', models.CharField(blank=True, max_length=40)),
                ('adults', models.PositiveIntegerField(default=2)),
                ('children', models.PositiveIntegerField(default=0)),
                ('starting_location', models.CharField(blank=True, max_length=120)),
                ('duration_days', models.PositiveIntegerField(default=3)),
                ('destination_interest', models.JSONField(blank=True, default=list)),
                ('trip_type', models.CharField(max_length=80)),
                ('accommodation_level', models.CharField(max_length=80)),
                ('private_or_shared', models.CharField(max_length=20)),
                ('budget_min', models.PositiveIntegerField(default=0)),
                ('budget_max', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('verification_code', models.CharField(blank=True, max_length=4)),
                ('verification_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('unverified', 'Unverified'), ('verified', 'Verified'), ('contacted', 'Contacted'), ('quote_sent', 'Quote Sent'), ('booked', 'Booked'), ('closed', 'Closed')], default='unverified', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_name', models.CharField(max_length=120)),
                ('guest_country', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('review_text', models.TextField()),
                ('source', models.CharField(choices=[('Google', 'Google'), ('TripAdvisor', 'TripAdvisor'), ('Direct Guest', 'Direct Guest')], max_length=40)),
                ('review_date', models.DateField()),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-review_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('duration_days', models.PositiveIntegerField()),
                ('duration_nights', models.PositiveIntegerField()),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('featured_image', models.URLField()),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('travel_style', models.CharField(max_length=80)),
                ('private_or_shared', models.CharField(max_length=20)),
                ('accommodation_type', models.CharField(max_length=80)),
                ('itinerary_json', models.JSONField(blank=True, default=list)),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('exclusions', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('destinations', models.ManyToManyField(related_name='tour_packages', to='api.destination')),
            ],
            options={
                'ordering': ['duration_days', 'price_from'],
            },
        ),
    ]
